apiVersion: v2
name: drill
version: 1.2.10
appVersion: 1.21.1
description: Helm Charts for deploying Apache Drill Clusters on Kubernetes
icon: https://raw.githubusercontent.com/wearefrank/charts/master/charts/drill/icon.svg
type: application
keywords:
  - apache
  - drill
  - data
  - query
home: 'https://drill.apache.org/'
sources:
  - 'https://github.com/wearefrank/charts'
dependencies:
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.2
